### PR TITLE
made invisible sections with users/watchers in sub menu until be thou…

### PR DESCRIPTION
**Pull request by manmorc**
…ght out

https://github.com/linnovate/root/issues/1039

### CODE REVIEW

**Comment by nevos** [comment]
can we make instead -<div class="watchers-wrapper" ng-hide="true"> 
?

**Comment by nevos** [comment]
@manmorc .... see comment

**Comment by nevos** [comment]
@manmorc see my comment

**Comment by manmorc** [comment]
@nevos done

**Pull request merged**
